DELETE http://localhost:3000/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIxLCJlbWFpbCI6Im92ZXIxMDA1MDB5MHVybG9yZDJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MzQ2NTk5NzUsImV4cCI6MTczNDY2MzU3NSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.ndjm-oJJhumI8yFuk1503EEq5_3IoHk2UIWoJ7fo4NE
    ?id=2