POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImlhdCI6MTczNDU4MDc3NiwiZXhwIjoxNzM0NjY3MTc2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.fqzdTHogv-aik_1xVazyONfUwZlFH4JR57XHnauJb7o"
}