GET http://localhost:3000/comments?productId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwLCJlbWFpbCI6Im92ZXIxMDA1MDB5MHVybG9yZDFAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM0NjUxMjI4LCJleHAiOjE3MzQ2NTQ4MjgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.pZz1Ltc3t6satKhIyPPBhy-5RImJ0a4X0Ow3bitV6NE